### ISSUE TITLE
What draft version is used?

### ISSUE THREAD

**Issue by jelu** [dns-stats/compactor#23]
I think it would be wise if you mention what version of the draft is used at all the places where the draft is mentioned.

Took me 10+ mins to dig into documents to see any mentioning of draft version.

Would also be a good idea to have this information displayed in the `--version` output of the tools.

**Comment by banburybill** [comment]
Good point.

For the record, compactor/inspector are still on draft version 04. Subsequent draft versions contain some non-trivial changes; we intend to update, but not until we are confident that the draft has stabilised.

We'll document this more clearly for the release.

**Comment by jelu** [comment]
> For the record, compactor/inspector are still on draft version 04.
Then it really needs an update because what I found was version 2.

**Comment by banburybill** [comment]
Docs updated and `compactor --version` also reports draft.
