### ISSUE TITLE
Section "Reconstructed PCAP files" missing

### ISSUE THREAD

**Issue by jelu** [dns-stats/compactor#24]
The [overview](https://github.com/dns-stats/compactor/blob/master/doc/user-guide/overview.adoc) documentation mentions the section about limitation in reconstructing PCAPs but that section is missing.

**Comment by banburybill** [comment]
The link works in the release HTML user-guide.html and PDF user-guide.pdf. But if you're viewing .adocs separately via GitHub, that section is now in https://github.com/dns-stats/compactor/blob/master/doc/user-guide/running.adoc and so the link fails. I'll update the cross-reference to include the target file. Hopefully that'll fix it in this case.
