### ISSUE TITLE
Clarify what parts are covered by OpenSSL license

### ISSUE THREAD

**Issue by pspacek** [dns-stats/compactor#55]
Hello,

could you please clarify what files (or parts of files) are covered by OpenSSL license? I did not find that information in file headers.

According to https://www.gnu.org/licenses/license-list.html.en OpenSSL license is incompatible with GNU GPL so the code cannot be used in GNU GPL licensed software, e.g. Knot DNS.

Knowing which parts of compactor code base are incompatible is crucial for decision whether we can easily replace them with another implementation or if we need to write our own compactor from scratch.

Thank you for your time.

**Comment by banburybill** [comment]
Hi Petr,

If (and only if) IP address pseudo-anonymisation is enabled, we're using AES functions from libcrypto in the address pseudoanonymisation code. Specifically:

AES_set_encrypt_key()
AES_encrypt()
PKCS5_PBKDF2_HMAC_SHA1()

OpenSSL from 3.0 is Apache licensed. Prior versions had the OpenSSL/SSLeay dual licence, and the latter includes an attribution clause. That's the reason we included the OpenSSL licence. We do need to update the text in LICENSE.txt to include the OpenSSL >=3.0 licence position.

I hope that helps.

**Comment by pspacek** [comment]
I see, so it is "just" the linking. Thank you for clarification.
