### ISSUE TITLE
no-compile-doc

### ISSUE THREAD

**Issue by huitema** [dns-stats/compactor#61]
I just cloned the compactor repo in the hope of compiling locally, but no such luck. I see multiple files that surely play a role in preparing to compile and make, `autogen.sh`, `configure.ac`, `Makefile.am`, even `README.adoc`. I suppose that I have to use a combination of autoconf, autogen and make. But it would be very nice if that configuration was explained somewhere...

**Comment by banburybill** [comment]
There is documentation in the user guide on building from scratch, in `doc/user-guide/installation.adoc.in`, but we should add an extract for those cloning from Github that's more obviously visible in the main project directory. Basically you want this:

`$ ./autogen.sh
$ ./configure
$ make
$ make install`

There's a few build pre-requisites. The user guide gives the details, but of course there's a Catch-22 in that you need to configure and build to get the nicely formatted user guide...

**Comment by huitema** [comment]
I am working my way through the dependencies. I started with a minimal Ubuntu 19 VM, and so far I have added:
```
sudo apt-get install git
sudo apt-get install build-essential
sudo apt-get install autogen
sudo apt-get install autoconf
sudo apt-get install libtool
sudo apt-get install libtool-bin
sudo apt-get install libtool-doc
sudo apt-get install libboost-all-dev
sudo apr-get install liblzma-dev
sudo apr-get install libtins-dev
```
I have cloned the repo, run autogen. I am getting a complaint that "ctemplate" is missing. Where do I find that?

**Comment by saradickinson** [comment]
@huitema There is also a PDF version of the documentation available https://github.com/dns-stats/compactor/wiki/user-guide.pdf and Jim's just added an INSTALL file to the develop branch.

**Comment by huitema** [comment]
@banburybill Great. The proposed INSTALL file would have solved a lot of my problems. I left a comment on the commit suggesting a few improvements.

@saradickinson The user guide is also very helpful. My first attempt at compacting a PCAP file resulted in a very tiny file, presumably because a lot of fields were excluded. Using the "-n all" option as suggested in the guide makes the file 3 times larger, which seems more realistic. Did you add a pointer to the guide in the README?

**Comment by saradickinson** [comment]
@huitema Yes - https://github.com/dns-stats/compactor/commit/4d469542e6cd868ff46f72a76643df43a9a29dd7 updated the README to reference both the User Guide and the INSTALL file. Thanks for all the feedback.

**Comment by huitema** [comment]
I think this issue is fixed. Close it when you want.
