### ISSUE TITLE
No rule to make target `dnstap/dnstap.proto`

### ISSUE THREAD

**Issue by ltfiend** [dns-stats/compactor#70]
Getting the following error building:

```make: *** No rule to make target `dnstap/dnstap.proto', needed by `dnstap/dnstap.pb.h'. Stop.```

Thank you

**Comment by ltfiend** [comment]
Didn't realize the dnstap.proto file wasn't in the release tar.gz.  I've pulled it separately.

**Comment by banburybill** [comment]
On 21 April 2021 19:01:39 BST, ltfiend ***@***.***> wrote:
>Didn't realize the dnstap.proto file wasn't in the release tar.gz. 
>I've pulled it separately.

The official release tarball should contain dnstap.proto. Was this the Github generated tarball.?
-- 
Sent from a computer I can lift.

**Comment by ltfiend** [comment]
> On 21 April 2021 19:01:39 BST, ltfiend ***@***.***> wrote: Didn't realize the dnstap.proto file wasn't in the release tar.gz. I've pulled it separately.
> The official release tarball should contain dnstap.proto. Was this the Github generated tarball.?

Yes, these are the github generated ones now that I pay closer attention.   The indicator seems to be the filename.  If it's "compactor...." it won't have the .proto file.  If it's dns-stats-compactor as you would download from wiki -> releases then it does.

**Comment by banburybill** [comment]
On 22 April 2021 11:17:04 BST, ltfiend ***@***.***> wrote:
>> On 21 April 2021 19:01:39 BST, ltfiend ***@***.***> wrote: Didn't
>realize the dnstap.proto file wasn't in the release tar.gz. I've pulled
>it separately.
>> The official release tarball should contain dnstap.proto. Was this
>the Github generated tarball.?
>
>Yes, these are the github generated ones now that I pay closer
>attention.   The indicator seems to be the filename.  If it's
>"compactor...." it won't have the .proto file.  If it's
>dns-stats-compactor as you would download from wiki -> releases then it
>does.  

Thanks. Yes, the Github generated ones are misleading. I wish I could disable them.
