### ISSUE TITLE
configure --disable-pseudo-anonymisation fails at build time

### ISSUE THREAD

**Issue by SeanBurford** [dns-stats/compactor#75]
inspector.cpp contains an unconditional call to pseudo_anon_key.size() a bit after line 372.  This call should be wrapped in an `#if ENABLE_PSEUDOANONYMISATION`.  Without the conditional compilation fails if configure is run as `configure --disable-pseudo-anonymisation`.

**Comment by saradickinson** [comment]
Thanks! https://github.com/dns-stats/compactor/commit/4c50ac034f121e3bfcd42cd2956392760866e6b3 should fix this.

**Comment by saradickinson** [comment]
Fixed in 1.2.1
